version: '3.8'

services:
  #php
  app:
    build:
      dockerfile: ./src/Dockerfile
    ports:
        - 8000:80
    volumes:
        - /var/www/html/vendor
        - ./src/app:/var/www/html
        - ./src/apache:/etc/apache2/sites-enabled
    networks:
        - dev
    depends_on:
        - db
      
  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
    ports:
      - "4406:3306"
    restart: unless-stopped
    volumes:
      - "./db:/docker-entrypoint-initdb.d" 
    networks:
      - dev


networks:
   dev:
 